version: '3'
networks:
  app:
services:
  backend:
    image: node:12.7.0-buster
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
    depends_on:
      - database
    working_dir: /usr/app
    command: bash init.sh
    networks:
      - app
    environment:
      - MONGO_URL=mongodb://database/codeshift
      - JWT_SESSION=amoeba
  database:
    image: mongo:3.4.22-xenial
    restart: always
    networks: 
      - app
  server:
    image: nginx:1.17.3
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app
    depends_on:
      - backend
      - database